# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b164be916a232db94d924e1cde90f7e44373e8275aa92ed1c84a64a229cb3e100e60de6429923b899557b15f88e82322393296c1ea26d087403f6da162a235e2

test:
  secret_key_base: 3ae32c187eb0c316d02088ae21718aae70d55c5cfcf610f8c32ba7373555cb20e4950f74a5d406571e2b416025932d3da78b0172103984b436a99329d8e171a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
